language: node_js
node_js:
  - 8
services:
  - docker
env:
  global:
  - secure: travisEncryptedAWS_ACCOUNT_ID
  - secure: travisEncryptedAWS_DEFAULT_REGION
  - secure: travisEncryptedAWS_ACCESS_KEY_ID
  - secure: travisEncryptedAWS_SECRET_ACCESS_KEY
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin  
before_script:
  - npm install
script:
  - eval $(aws ecr get-login --region eu-west-3 --no-include-email)
  - aws ecr batch-delete-image --repository-name novelshiveapi --image-ids imageTag=latest
  - docker build -t novelshiveapi:latest .
  - docker tag novelshiveapi:latest 499596517866.dkr.ecr.eu-west-3.amazonaws.com/novelshiveapi:latest
  - docker push 499596517866.dkr.ecr.eu-west-3.amazonaws.com/novelshiveapi:latest
  - aws ecs update-service --cluster novels-hive --service novels-hive-api --force-new-deployment
